import { zodResolver } from "@hookform/resolvers/zod";
import { AlertTriangle, CalendarDays, HeartPulse, ShieldAlert, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { api, CyclePrediction, PCOSPrediction, PPDAssessment } from "@/lib/api";
import { CalendarGrid } from "@/components/common/CalendarGrid";
import { FormField, TextAreaField } from "@/components/common/FormField";
import { IconNote, StatTile } from "@/components/common/InfoBlocks";
import { DataTable, Gauge, MetricCard, SectionHeader } from "@/components/common/Premium";
import { Page } from "@/components/common/Page";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";

const pcosSchema = z.object({ age: z.number().min(10, "Age must be at least 10.").max(60, "Age must be 60 or below."), bmi: z.number().positive("BMI must be greater than 0.").max(80, "BMI must be 80 or below."), cycleLength: z.number().min(15, "Cycle length must be at least 15 days.").max(90, "Cycle length must be 90 days or below."), follicleCount: z.number().min(0, "Follicle count cannot be negative.").max(100, "Follicle count must be 100 or below."), cycleIrregularity: z.boolean().default(false), hairGrowth: z.boolean().default(false), skinDarkening: z.boolean().default(false), weightGain: z.boolean().default(false) });
type PCOSForm = z.infer<typeof pcosSchema>;

export function PCOSPage() {
  const [result, setResult] = useState<PCOSPrediction | null>(null);
  const [history, setHistory] = useState<PCOSPrediction[]>([]);
  const [error, setError] = useState("");
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<PCOSForm>({ resolver: zodResolver(pcosSchema), defaultValues: { age: 28, bmi: 23, cycleLength: 29, follicleCount: 8 } });
  useEffect(() => { api.pcosHistory().then(setHistory).catch(() => undefined); }, []);
  async function submit(values: PCOSForm) { setError(""); try { const prediction = await api.predictPCOS({ age: values.age, bmi: values.bmi, cycle_irregularity: values.cycleIrregularity, hair_growth: values.hairGrowth, skin_darkening: values.skinDarkening, weight_gain: values.weightGain, follicle_count: values.follicleCount }); setResult(prediction); setHistory((items) => [prediction, ...items]); } catch (reason) { setError(reason instanceof Error ? reason.message : "Prediction failed"); } }
  return <Page title="PCOS Prediction" subtitle="Submit your indicators to receive a stored screening result and recommendations."><div className="grid gap-6 xl:grid-cols-[420px_minmax(0,1fr)]"><Card><form onSubmit={handleSubmit(submit)}><SectionHeader title="Prediction Form" subtitle="Structured symptoms and clinical indicators" /><div className="space-y-4">{[["Age", "age"], ["BMI", "bmi"], ["Cycle length", "cycleLength"], ["Follicle count", "follicleCount"]].map(([label, name]) => { const fieldName = name as "age" | "bmi" | "cycleLength" | "follicleCount"; return <FormField key={name} label={label} type="number" error={errors[fieldName]?.message} {...register(fieldName, { valueAsNumber: true })} />; })}{[["Cycle irregularity", "cycleIrregularity"], ["Excess hair growth", "hairGrowth"], ["Skin darkening", "skinDarkening"], ["Recent weight gain", "weightGain"]].map(([label, name]) => <label key={label} className="flex items-center justify-between gap-4 rounded-[20px] border border-white/70 bg-pink-50/80 p-4 text-sm font-black text-ink dark:border-white/10 dark:bg-white/10 dark:text-white">{label}<input type="checkbox" className="h-5 w-5 shrink-0 accent-primary" {...register(name as keyof PCOSForm)} /></label>)}{error ? <p className="text-sm font-bold text-danger">{error}</p> : null}<Button className="w-full" disabled={isSubmitting}>{isSubmitting ? "Running..." : "Run Prediction"}</Button></div></form></Card><div className="space-y-6"><PCOSResult result={result} /><DataTable rows={history.map((item) => ({ date: new Date(item.created_at).toLocaleDateString(), risk: item.risk_level, probability: `${Math.round(item.probability * 100)}%` }))} columns={["date", "risk", "probability"]} /></div></div></Page>;
}

function PCOSResult({ result }: { result: PCOSPrediction | null }) { if (!result) return <Card><SectionHeader title="Your result" subtitle="Run a prediction to see the returned screening result." /><IconNote icon={HeartPulse} title="No prediction yet" text="This screening supports clinical conversations and does not diagnose PCOS." /></Card>; const percentage = Math.round(result.probability * 100); return <Card className="overflow-hidden"><div className="grid gap-6 md:grid-cols-[250px_1fr]"><div className="rounded-[28px] bg-gradient-to-br from-pink-50 to-purple-50 p-5 dark:from-white/10 dark:to-white/5"><HeartPulse className="mx-auto mb-3 h-10 w-10 text-primary" /><Gauge value={percentage} label={`${result.risk_level} risk`} /></div><div><Badge className="bg-emerald-50 text-emerald-700">Returned from API</Badge><h3 className="mt-3 text-2xl font-black text-ink dark:text-white">Recommendation Summary</h3><p className="mt-3 text-sm leading-6 text-muted dark:text-white/60">{result.recommendations}</p><Progress value={percentage} className="mt-5" /></div></div></Card>; }

const epdsQuestions = ["I have felt able to laugh and see the funny side of things.", "I have looked forward with enjoyment to things.", "I have blamed myself unnecessarily when things went wrong.", "I have felt anxious or worried for no good reason.", "I have felt scared or panicky for no very good reason.", "Things have been getting on top of me.", "I have been so unhappy that I have had difficulty sleeping.", "I have felt sad or miserable.", "I have been so unhappy that I have been crying.", "The thought of harming myself has occurred to me."];

export function PPDPage() {
  const [answers, setAnswers] = useState<number[]>(Array(10).fill(0)); const [result, setResult] = useState<PPDAssessment | null>(null); const [history, setHistory] = useState<PPDAssessment[]>([]); const [journal, setJournal] = useState(""); const [error, setError] = useState("");
  useEffect(() => { api.ppdHistory().then(setHistory).catch(() => undefined); }, []);
  async function submit() { setError(""); try { const assessment = await api.assessPPD(answers, journal || null); setResult(assessment); setHistory((items) => [assessment, ...items]); } catch (reason) { setError(reason instanceof Error ? reason.message : "Assessment failed"); } }
  return <Page title="PPD Detection" subtitle="Complete the ten-item EPDS assessment to receive a stored result and follow-up guidance."><div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]"><Card><SectionHeader title="EPDS Questionnaire" subtitle="Ten questions required by the assessment API" /><Progress value={100} /><div className="mt-6 space-y-4">{epdsQuestions.map((question, index) => <div key={question} className="rounded-[22px] bg-pink-50/80 p-4 dark:bg-white/10"><p className="font-black text-ink dark:text-white">{index + 1}. {question}</p><div className="mt-4 grid gap-2 sm:grid-cols-4">{[0, 1, 2, 3].map((value) => <Button key={value} variant={answers[index] === value ? "primary" : "secondary"} onClick={() => setAnswers((items) => items.map((item, itemIndex) => itemIndex === index ? value : item))}>{value}</Button>)}</div></div>)}</div><TextAreaField className="mt-5" label="Optional journal context" value={journal} onChange={(event) => setJournal(event.target.value)} placeholder="Share anything you want the assessment to consider..." />{error ? <p className="mt-3 text-sm font-bold text-danger">{error}</p> : null}<Button className="mt-4 w-full" onClick={() => void submit()}>Submit EPDS Assessment</Button></Card><div className="space-y-6">{result ? <MetricCard label="Current Result" value={result.risk_level} icon={ShieldAlert} progress={Math.min(100, result.epds_score * 100 / 30)} note={`EPDS score ${result.epds_score}; sentiment ${result.sentiment}`} tone="from-sky to-accent" /> : <Card><SectionHeader title="Current result" /><IconNote icon={ShieldAlert} title="No assessment yet" text="Complete all ten questions and submit to receive the backend result." /></Card>}<DataTable rows={history.map((item) => ({ date: new Date(item.created_at).toLocaleDateString(), score: item.epds_score, risk: item.risk_level }))} columns={["date", "score", "risk"]} /></div></div></Page>;
}

export function CyclePage() {
  const [prediction, setPrediction] = useState<CyclePrediction | null>(null); const [error, setError] = useState(""); const [date, setDate] = useState(""); const [length, setLength] = useState(28);
  useEffect(() => { api.cyclePrediction().then(setPrediction).catch(() => undefined); }, []);
  async function submit() { setError(""); try { await api.createCycle(date, length); setPrediction(await api.cyclePrediction()); } catch (reason) { setError(reason instanceof Error ? reason.message : "Cycle entry failed"); } }
  return <Page title="Cycle Tracker" subtitle="Save a period start date and view the backend prediction."><div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]"><Card><SectionHeader title="Log a cycle" subtitle="Your entries are saved to your wellness record." /><div className="space-y-4"><FormField label="Last period date" type="date" value={date} onChange={(event) => setDate(event.target.value)} /><FormField label="Cycle length" type="number" min={15} max={60} value={length} onChange={(event) => setLength(Number(event.target.value))} />{error ? <p className="text-sm font-bold text-danger">{error}</p> : null}<Button className="w-full" disabled={!date} onClick={() => void submit()}>Save Cycle</Button></div></Card><div className="space-y-6"><Card><CalendarDays className="mb-4 h-9 w-9 text-primary" />{prediction ? <>{[["Next period", prediction.next_period_prediction], ["Ovulation", prediction.ovulation_prediction], ["Fertility window", `${prediction.fertility_window_start} - ${prediction.fertility_window_end}`], ["Cycle length", `${prediction.cycle_length} days`]].map(([label, value]) => <StatTile key={label} label={label} value={value} className="mb-3" />)}</> : <IconNote icon={CalendarDays} title="No cycle prediction" text="Log your last period to calculate an estimate." />}</Card>{prediction ? <Card><SectionHeader title="Prediction calendar" subtitle="Estimated cycle window" /><CalendarGrid activeFrom={1} activeTo={prediction.cycle_length} monthDays={prediction.cycle_length} /></Card> : null}</div></div></Page>;
}

export function EmergencyPage() { return <Page title="Emergency Help" subtitle="High-visibility support for urgent symptoms and care escalation."><Card className="overflow-hidden bg-gradient-to-br from-rose-600 via-primary to-accent p-8 text-white"><AlertTriangle className="mb-4 h-12 w-12" /><h2 className="text-3xl font-black md:text-5xl">Get urgent medical care</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-white/85 md:text-base">Heavy bleeding, severe pain, fainting, breathing difficulty, seizures, chest pain, or self-harm thoughts need immediate professional help.</p><div className="mt-7 flex flex-wrap gap-3"><Button variant="secondary" onClick={() => window.open("tel:112")}>Call emergency services</Button><Button variant="secondary"><Sparkles className="h-4 w-4 text-primary" />Share Location</Button></div></Card></Page>; }
