import { Activity, Bell, CheckCircle2, FileText, Lock, Settings as SettingsIcon, ShieldCheck, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { api, Alert, CaregiverContent, ChatMessage, HighRiskCase } from "@/lib/api";
import { IconNote, StatTile } from "@/components/common/InfoBlocks";
import { EmptyState, LoadingSkeleton } from "@/components/common/States";
import { Page } from "@/components/common/Page";
import { DataTable, MetricCard, SectionHeader, Timeline } from "@/components/common/Premium";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { useAuth } from "@/context/useAuth";

export function InsightsPage() {
  const [data, setData] = useState<Record<string, unknown> | null>(null);
  useEffect(() => { api.analytics().then(setData).catch(() => undefined); }, []);
  return <Page title="Health Insights" subtitle="Analytics returned from your wellness records.">{data ? <Card><SectionHeader title="Mother analytics" subtitle="Current backend summary" /><pre className="overflow-auto rounded-2xl bg-pink-50 p-4 text-xs text-ink dark:bg-white/10 dark:text-white">{JSON.stringify(data, null, 2)}</pre></Card> : <LoadingSkeleton />}</Page>;
}

export function JournalPage() {
  const [mood, setMood] = useState("happy"); const [note, setNote] = useState(""); const [entries, setEntries] = useState<{ title: string; detail: string; time: string }[]>([]); const [error, setError] = useState("");
  useEffect(() => { api.journals().then((items) => setEntries(items.map((item) => ({ title: item.title, detail: item.content, time: new Date(item.created_at).toLocaleDateString() })))).catch(() => undefined); }, []);
  async function save() { try { const item = await api.createJournal(`Mood: ${mood}`, note); setEntries((items) => [{ title: item.title, detail: item.content, time: "Today" }, ...items]); setNote(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Journal save failed"); } }
  return <Page title="Mood Journal" subtitle="Private entries saved to your wellness record."><div className="grid gap-6 xl:grid-cols-[420px_minmax(0,1fr)]"><Card><SectionHeader title="How do you feel?" subtitle="Choose a mood and add a note" /><div className="grid grid-cols-5 gap-3">{["happy", "sad", "anxious", "tired", "angry"].map((value) => <button key={value} type="button" onClick={() => setMood(value)} className={`rounded-[20px] p-4 text-sm font-black capitalize ${mood === value ? "bg-primary text-white" : "bg-pink-50 text-muted dark:bg-white/10"}`}>{value}</button>)}</div><textarea className="mt-5 min-h-40 w-full rounded-[24px] border border-pink-100 bg-white/80 p-4 text-sm outline-none dark:border-white/10 dark:bg-white/10 dark:text-white" value={note} onChange={(event) => setNote(event.target.value)} placeholder="Write your private note..." />{error ? <p className="mt-3 text-sm font-bold text-danger">{error}</p> : null}<Button className="mt-4 w-full" disabled={!note.trim()} onClick={() => void save()}><CheckCircle2 className="h-4 w-4" />Save Journal</Button></Card><Card><SectionHeader title="Timeline" subtitle="Recent journal records" />{entries.length ? <Timeline items={entries} /> : <EmptyState />}</Card></div></Page>;
}

export function NutritionPage() { return <Page title="Nutrition Guide" subtitle="Nutrition data is not represented by a dedicated backend endpoint yet."><Card><IconNote icon={FileText} title="Guide content unavailable" text="The current API does not expose nutrition plans or nutrition logs." /></Card></Page>; }

export function CaregiverPage() { const [items, setItems] = useState<CaregiverContent[]>([]); useEffect(() => { Promise.all([api.caregiver("videos"), api.caregiver("tips"), api.caregiver("articles")]).then((groups) => setItems(groups.flat())).catch(() => undefined); }, []); return <Page title="Caregiver Zone" subtitle="Educational content returned by the caregiver API."><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{items.length ? items.map((item) => <Card key={item.id}><Badge>{item.category}</Badge><h2 className="mt-3 text-lg font-black text-ink dark:text-white">{item.title}</h2><p className="mt-2 text-sm leading-6 text-muted dark:text-white/60">{item.description}</p></Card>) : <EmptyState title="No caregiver content" text="No content is available for this account." />}</div></Page>; }

export function ASHAPage() { const [cases, setCases] = useState<HighRiskCase[]>([]); const [stats, setStats] = useState<Record<string, unknown> | null>(null); const [alerts, setAlerts] = useState<Alert[]>([]); useEffect(() => { api.ashaCases().then(setCases).catch(() => undefined); api.ashaStatistics().then(setStats).catch(() => undefined); api.ashaAlerts().then(setAlerts).catch(() => undefined); }, []); return <Page title="ASHA Dashboard" subtitle="Live high-risk cases and alert records."><div className="grid gap-4 md:grid-cols-3"><MetricCard label="High-risk cases" value={String(stats?.high_risk_cases ?? cases.length)} icon={ShieldCheck} note="From ASHA statistics" tone="from-primary to-accent" /><MetricCard label="Alerts" value={String(alerts.length)} icon={Bell} note="Stored alert records" tone="from-sky to-mint" /><MetricCard label="Open cases" value={String(cases.filter((item) => item.status.toLowerCase() === "open").length)} icon={Activity} note="Current queue" tone="from-rose-400 to-primary" /></div><div className="mt-6"><DataTable title="High-Risk Queue" rows={cases.map((item) => ({ case: item.id, user: item.user_id, risk: item.risk_level, source: item.risk_type, status: item.status }))} columns={["case", "user", "risk", "source", "status"]} /></div></Page>; }

export function ReportsPage() { const [data, setData] = useState<Record<string, unknown> | null>(null); useEffect(() => { api.analytics().then(setData).catch(() => undefined); }, []); return <Page title="Reports" subtitle="Available analytics from the wellness API."><Card><SectionHeader title="Wellness analytics" subtitle="No report-download endpoint exists in the current backend." />{data ? <pre className="overflow-auto rounded-2xl bg-pink-50 p-4 text-xs text-ink dark:bg-white/10 dark:text-white">{JSON.stringify(data, null, 2)}</pre> : <LoadingSkeleton />}</Card></Page>; }

export function ProfilePage() { const { user } = useAuth(); return <Page title="Profile" subtitle="Current account details from authentication."><div className="grid gap-6 xl:grid-cols-[360px_minmax(0,1fr)]"><Card className="text-center"><div className="mx-auto flex h-24 w-24 items-center justify-center rounded-[28px] bg-gradient-to-br from-primary to-accent text-white shadow-glow"><UserRound className="h-12 w-12" /></div><h2 className="mt-4 text-xl font-black text-ink dark:text-white">{user?.name}</h2><p className="text-sm font-semibold text-muted dark:text-white/60">{user?.role} · {user?.preferred_language}</p><Badge className="mt-4">Authenticated</Badge></Card><Card><SectionHeader title="Account details" subtitle="Read from /auth/me" /><div className="grid gap-4 md:grid-cols-2"><StatTile label="Email" value={user?.email ?? ""} /><StatTile label="Phone" value={user?.phone ?? "Not provided"} /><StatTile label="Role" value={user?.role ?? ""} /><StatTile label="Language" value={user?.preferred_language ?? ""} /></div><IconNote className="mt-5" icon={Lock} title="Profile editing unavailable" text="The current backend has no profile update endpoint." /></Card></div></Page>; }

export function SettingsPage() { return <Page title="Settings" subtitle="Account controls available through the existing API."><Card><IconNote icon={SettingsIcon} title="Settings endpoint unavailable" text="Notification and privacy preferences are not exposed by the current backend contract." /></Card></Page>; }
export function ChatHistoryPage() { const [items, setItems] = useState<ChatMessage[]>([]); useEffect(() => { api.chatHistory().then(setItems).catch(() => undefined); }, []); return <Page title="Chat History" subtitle="Previous AI coach conversations from the backend."><div className="space-y-4">{items.length ? items.map((item) => <Card key={item.id}><h2 className="font-black text-ink dark:text-white">{item.message}</h2><p className="mt-2 text-sm leading-6 text-muted dark:text-white/60">{item.response}</p></Card>) : <EmptyState title="No conversations yet" />}</div></Page>; }
export function LogoutPage() { const { signOut } = useAuth(); return <Page title="Logout"><Card className="flex min-h-64 flex-col items-center justify-center text-center"><IconNote icon={CheckCircle2} title="End this session" text="Revoke the current refresh token." /><Button className="mt-5" onClick={() => void signOut()}>Sign out</Button></Card></Page>; }
export function NotFoundPage() { return <Page title="Page not found"><EmptyState title="Nothing here" text="Return to the dashboard to continue." /></Page>; }
